### ISSUE TITLE
How to install theme?

### ISSUE THREAD

**Issue by shhivam** [addy-dclxvi/xfwm4-theme-collections#2]
Hey!
I am new to Ubuntu. I want  to try one of your themes on my machine.
and I don't know how to.

I have downloaded xubuntu-desktop using sudo apt-get command.
Cloned your repo in ~/.themes directory.

What next?

I know that this is not the right place to ask this but a little help will be appreciated.

**Comment by addy-dclxvi** [comment]
Go to Xfce4 Settings Manager, then Window Manager, then apply one.
