### ISSUE TITLE
Emoji are shown in the title bar

### ISSUE THREAD

**Issue by Mati20187** [addy-dclxvi/xfwm4-theme-collections#4]
Hi, I've noticed that you use the same color for the title bar and the text to hide the title. However, sometimes I'm in a situation where the title contains emoji (watching YouTube videos in MPV) and they are visible. Is there a way to stop the emojis from showing?

**Comment by addy-dclxvi** [comment]
Actually I use Xfconf to set the font size to zero

https://github.com/addy-dclxvi/almighty-dotfiles/blob/master/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml#L62

**Comment by Mati20187** [comment]
After setting the font size to 0, everything works perfectly. Thanks!

**Comment by addy-dclxvi** [comment]
OK you're welcome!

**Comment by tuschla** [comment]
Hi, I set the title_font attribute to 0 as shown in your config but it somehow still shows up :(

**Comment by tuschla** [comment]
Ok, rebooting did the trick.
