### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Javi3y** [addy-dclxvi/xfwm4-theme-collections#8]

**Comment by Javi3y** [comment]
hey i want to add gaps to an existing xfwm4 theme how can i do it
this is my theme file:
[themerc.txt](https://github.com/addy-dclxvi/xfwm4-theme-collections/files/7224651/themerc.txt)

**Comment by Acvale** [comment]
You must edit the .png files with a program like Krita. Mess with them a little until you get the logic behind them. After that you may have to change the shadow values in the themerc.txt.

It's a lot easier to use KDE + Krohnkite, so this is an alternative if you aren't bounded to xfce for some reason.

**Comment by Javi3y** [comment]
oh thanks alot
i actually was forced to distro hop and now i have plasma :)
